### PR TITLE
Loading app with contrast theme instead of normal

### PR DESCRIPTION
**Pull request by rake7h**
Load app with contrast theme instead of normal on load
-replace scss files with contrast one
-change the theme toggle button label according to active theme

### CODE REVIEW

**Review by qiell — CHANGES_REQUESTED** [review]
Remove the extra space.
Rest all looks good to me.

**Review by qiell — APPROVED** [review]
lgtm

**Comment by satyamz** [comment]
@visualapps I am just wondering whether this is good idea because, when we run it in the contrast mode we get a white box created on the terminal. I think before merging this, we better have a solution for previously mentioned issue.

**Comment by rake7h** [comment]
@satyamz now we can merge this with changes #109

**Pull request merged**
